### ISSUE TITLE
 gl.glClearColor error 

### ISSUE THREAD

**Issue by hanpeetermans** [david-svitov/fishscanner#11]
When I try to run your code I get an OpenGL error.
Have I done something wrong?

************************************
Traceback (most recent call last):
  File "main_ocean.py", line 293, in <module>
    main()
  File "main_ocean.py", line 269, in main
    gl.glClearColor(0.1, 0.1, 0.2, 1.0)
  File "C:\Users\user\anaconda3\envs\FishScanner\lib\site-packages\OpenGL\platform\baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "C:\Users\user\anaconda3\envs\FishScanner\lib\site-packages\OpenGL\error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'ongeldige bewerking',
        baseOperation = glClearColor,
        cArguments = (0.1, 0.1, 0.2, 1.0)
)

**Comment by david-svitov** [comment]
Seems like OpenGL installation problem. First check that you use the same version as in requirements.txt. And if you use Windows check that you have all necessary dll files

**Comment by pessarrodona** [comment]
Hi, sorry I have exactly the same problem and I'm new at this. 

How do you force the computer to use the same OpenGL version as requirements.txt? Cause I thought that was implicit after installing the requirements.tx.
And also, how do you check that you have this necessary dll files that you mention? 

THANKS a lot

**Comment by car6130** [comment]
Was this ever resolved? I am also struggling with understanding the dll files.

**Comment by david-svitov** [comment]
@car6130  If I make a Docker container, will it help you?

**Comment by david-svitov** [comment]
Ah. DLL. I see. I don't have universal advice on how to deal with Microsoft :)

**Comment by car6130** [comment]
@david-svitov The docker container may be helpful if you're willing to make it. Thank you. I do have access to another OS if that would also make it work.
