### ISSUE TITLE
runing error

### ISSUE THREAD

**Issue by manhole1** [david-svitov/fishscanner#12]
Traceback (most recent call last):
  File "main_ocean.py", line 294, in <module>
    main()
  File "main_ocean.py", line 270, in main
    gl.glClearColor(0.1, 0.1, 0.2, 1.0)
  File "C:\Users\admin\OpenGL\platform\baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'invalid operation',
        baseOperation = glClearColor,
        cArguments = (0.1, 0.1, 0.2, 1.0)
)

**Comment by achimonde** [comment]
I'm having the same issue. Is there any suggestions please?
